services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: airports
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: /app                 # 👈 para que "from app ..." funcione
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/airports
      APP_ENV: docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
